### ISSUE TITLE
The German alphabet has a new official letter the capital ẞ (U+1E9E)

### ISSUE THREAD

**Issue by getreu** [pieter-degroote/EurKEY-clone#1]
The German alphabet has a new official letter the capital ẞ (U+1E9E) for some years now.

In EurKey 1.3 beta it is mapped to AltGr-Shift-s. I suggest doing so here also.

**Comment by pieter-degroote** [comment]
All beta and draft versions of this clone project have the capital ẞ (u+1e9e) implemented.

This is also implemented in the latest releases of UltimateKEYS :

**Official release&nbsp;:**&emsp;[![GitHub Release](https://img.shields.io/github/release/pieter-degroote/UltimateKEYS.svg)](https://github.com/pieter-degroote/UltimateKEYS/releases)
**Testing release&nbsp;:**&emsp;[![GitHub Testing](https://img.shields.io/github/release/pieter-degroote/UltimateKEYS-testing.svg?label=testing)](https://github.com/pieter-degroote/UltimateKEYS-testing/releases)
